# Generated by Django 3.2.6 on 2021-09-09 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_userprofile_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderItem',
        ),
        migrations.AddField(
            model_name='order',
            name='orderItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='shop.orderitem'),
        ),
    ]
